### ISSUE TITLE
Cannot connect to mysqueezebox.com

### ISSUE THREAD

**Issue by pculebras** [Saiyato/volumio-lms-plugin#1]
I would like to use some addons, like the Tidal one, and sync is not working.

I checked the logs and it just complains that it can’t connect, so it stops trying.

Maybe upgrading to the latest version fixes the issue?

**Comment by Saiyato** [comment]
I just uploaded a new version of the plugin, there were some sync issues with github :(
This version grabs the 7.9.1 release instead, can you confirm this solves your problem?

**Comment by pculebras** [comment]
It is not available via the plugin manager. Maybe the zip file needs to be merged with volumios repo?

**Comment by Saiyato** [comment]
No it isn't, that version was patched long ago and is awaiting approval by Volumio. You can install the new version by using the zip file only.

**Comment by pculebras** [comment]
Where should I place the file to perform the upgrade?

**Comment by Saiyato** [comment]
You can just install the deb package from slimserver, that ought to update the existing installation.
Or you can remove everything and start over.

Instructions can be found here: https://volumio.org/forum/help-installing-plugin-from-zip-t9117.html and here: https://github.com/Saiyato/volumio-plugin-helper
