### ISSUE TITLE
Can't play anything if LMS is functioning!

### ISSUE THREAD

**Issue by GiDiPa** [Saiyato/volumio-lms-plugin#2]
Hi!! Hi wrote also for snapcast XD. I'm testing also this plugin but I've got a problem.
Setup:
1 RPI3 With LMS+Squeezelite player
2 RPI B+ With Squeezelite player

If I switch on RPI3 With LMS already setted up(and working of course), and I try to play something in Volumio(Volumio radios for example) , I've got Alsa error. And every sound gonna stop! Even Squeezelite installed in server. 

Hope i helped!

**Comment by Saiyato** [comment]
I think this is more of a squeezelite problem, which version of the Squeezelite plugin did you use?
I recently patched this behavior, see this commit: https://github.com/Saiyato/volumio-squeezelite-plugin/commit/480a877ed48730e76d6f6e91edd26aca727ca6ff
