### ISSUE TITLE
LMS and squeezeliteplayer both not working after updates

### ISSUE THREAD

**Issue by acetonixus** [Saiyato/volumio-lms-plugin#3]
Happily using LMS with volumio about 1 year now in synced multiroom setup.
After updating to the latest plugins on 08/12/2018, nothing worked anymore.
My troubleshooting steps:
- Wipe SD card and clean install latest volumio (2.513)
- Install plug-in LMS. Activate plugin, reboot. But I just can't get to the localhost:9000 page (100% sure ip address is correct). Page not found, also squeezer doesn't pick up any server.
- Install squeezelite player. Here I noticed that I can still play my music folder from Volumio. while it should give some error when squeezeliteplayer plugin is activated.

My guess is that the plugins are somehow not properly integrated, that somehow Volumio doesn't know the plugins are there (even though activated)

**Comment by Saiyato** [comment]
Confirmed and fixed, see PR: https://github.com/volumio/volumio-plugins/pull/282

I will patch those changes to this repo in a bit.

**Comment by acetonixus** [comment]
Tested again, clean install and download LMS plugin from volumio UI. Not working, can't reach the LMS interface (ip:9000)

**Comment by Saiyato** [comment]
How did you install?

**Comment by acetonixus** [comment]
Through the volumio user interface -> plugins -> search plugins -> LMS -> Not working. But I noticed it gets his sh files from volumio plugin location.

If I ssh and do `wget -O install-lms.sh https://raw.githubusercontent.com/Saiyato/volumio-lms-plugin/master/install.sh` then everything is working fine.

I guess many people that try to install the plugin the normal way (through volumio user interface) they will struggle.

**Comment by Saiyato** [comment]
This is how the Volumio repo works, we submit a PR, which will be tested and confirmed (or rejected) after which it will be merged into the repo. When it's in the repo you can install the easy way.

**Comment by FranzoisC** [comment]
Hello, 
I tried to install the plugin using the latest version of volumio and I can't connect to the LMS interface (connection refused).
If I understand what is said above, I should install directly from the repo here. Correct? 
I tried the command above from in acetonixus post, but it apparently only donwloads the plugin. Could you give me instructions on how to install the plugin (I am not linux savy at all).
Thanks!

**Comment by Saiyato** [comment]
Hi there,

The instructions should be all over the Volumio forums, easiest is if you just read this repo: https://github.com/Saiyato/volumio-plugin-helper

You are right in assessing that you need to install from the repo, as my PR has not been merged yet.
